name: CI

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'feature/*'
      - 'he0119/*'
  pull_request:
  release:
    types: [published]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/coolqbot
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment: dev
    needs: docker
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: TAG_NAME
          script: |
            cd coolqbot/dev
            sed -i "s#${{ github.event.release.tag_name }}/coolqbot:.*#${{ github.event.release.tag_name }}/coolqbot:dev#g" docker-compose.yml
            sudo docker-compose pull
            sudo docker-compose up -d

  deploy_prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment: prod
    needs: docker
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          envs: TAG_NAME
          script: |
            cd coolqbot/prod
            sed -i "s#${{ github.event.release.tag_name }}8/coolqbot:.*#${{ github.event.release.tag_name }}/coolqbot:$TAG_NAME#g" docker-compose.yml
            docker-compose pull
            docker-compose up -d
